### ISSUE TITLE
nextjs support ?

### ISSUE THREAD

**Issue by punjasin** [buildingwatsize/thaidatepicker-react#16]
i got 
./node_modules/react-datepicker/dist/react-datepicker.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/thaidatepicker-react/dist/index.modern.js

in original react-datepicker
they have component with no css in it and we can import css later to prevent this error

**Comment by buildingwatsize** [comment]
@punjasin  I'm so sorry to be late. I have a good news for everyone who still using my library. The new release (v1.0.x) will support NextJS by import this library by standalone (not require a css file anymore, but it's [customizable](https://github.com/buildingwatsize/thaidatepicker-react/blob/main/example/with-vite-antd-tailwind/src/components/CustomThaiDatePicker.css)).

So you can check this out via [CodeSandbox](https://codesandbox.io/s/thaidatepicker-react-nextjs-demo-euw5lt?file=/pages/index.js)

NOTE: please ensure to install the new version one. "v1.0.x".

Appreciate. if you have any question please feel free to let me know.
