### ISSUE TITLE
how to show displayFormat month thai?

### ISSUE THREAD

**Issue by teammy** [buildingwatsize/thaidatepicker-react#23]
สวัสดีครับ

ขออนุญาตสอบถามผู้จัดทำนิดนึงครับ
หากต้องการจะให้แสดงเดือนเป็นภาษาไทย ต้องตั้งค่า displayFormat อย่างไรครับ
พอดีผมพยายามดูตัวอย่างแล้ว มีแต่ที่เป็นภาษาอังกฤษครับ

รบกวนขอคำแนะนำด้วยครับ
ขอบคุณครับ

**Comment by buildingwatsize** [comment]
สวัสดีครับ จากคำถาม ได้ลองตั้งค่า Locale เป็นภาษาไทยหรือยังนะครับ โดยจะมีวิธีการตั้งค่าด้านล่างครับ

```js
import dayjs from "dayjs";
import "dayjs/locale/th";

dayjs.locale("th");
```

หากยังไม่ได้ อาจจะขอรบกวนเป็น Reproduce ให้ดูได้ไหมครับ อาจจะแปะโค้ดไว้ที่ Codepen, CodeSandbox อะไรก็ได้สักอันแล้วแชร์ลิ้งค์มาครับ จะได้ลองดูปัญหาแล้วหาวิธีแก้กันครับ

**Comment by teammy** [comment]
สวัสดีครับ
ขอโทษที่ตอบกลับช้าครับ

แก้ไขปัญหาได้แล้วครับ ตามคำแนะนำที่ให้มาเลยครับ

ขอบคุณมากๆ นะครับ 

ปล.มอบค่ากาแฟได้ตรงไหนครับ แหะๆ

**Comment by buildingwatsize** [comment]
โอ้ ขอบพระคุณมากครับ แค่มีคนเอาไปใช้งานจริงก็ดีใจแล้วครับ

หากต้องการสนับสนุน ขออนุญาตแปะ QR Promptpay ไว้ที่นี่นะครับ ขอบพระคุณอีกครั้งครับ

![image](https://user-images.githubusercontent.com/8654428/228406502-070e610c-f8d6-4b53-9f56-b83cb6b6cf87.png)
