### ISSUE TITLE
decreaseMonth, increaseMonth button make form submit

### ISSUE THREAD

**Issue by phoneee** [buildingwatsize/thaidatepicker-react#3]
คือเวลากดปุ่ม ซ้าย ขวา เปลี่ยนเดือน มันทำให้ form submit น่ะครับ มีวิธีแก้มั้ยครับ ตอนนี้เลยต้องเข้าไปเอา source มาใช้ เข้าไปแก้ตรง renderCustomHeader แล้วปิดปุ่มทิ้งไปก่อน

**Comment by buildingwatsize** [comment]
ขอบคุณพี่ @phoneee ด้วยนะครับที่แจ้งเข้ามา ตอนนี้ผมแก้ให้ไม่ trigger form submit แล้วครับ สามารถใช้งานได้เลยใน [v0.1.5](https://github.com/buildingwatsize/thaidatepicker-react/releases/tag/v0.1.5) ครับ

หากพบปัญหาการใช้งานด้านไหนอีก สามารถสร้าง issues ได้ตลอดเวลาเลยค้าบ ขออภัยที่เข้ามาเห็นช้าไปตั้ง 2 วันนะครับ (พอดีหยุดงานน่ะครับ)
