### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by Mizugorou** [buildingwatsize/thaidatepicker-react#4]
Hi, last month, I has installed version 0.1.1. For today, I've just reinstall to lastest 0.1.5 and get problem as below.

```
./node_modules/thaidatepicker-react/dist/index.modern.js 545:41
Module parse failed: Unexpected token (545:41)
You may need an appropriate loader to handle this file type.
|       setSelectedDate = _useState4[1];
| 
>   var yearBoundary = props.yearBoundary ?? 99;
|   var thisYear = dayjs().year();
|   var minYear = props.minDate ? dayjs(props.minDate).year() : thisYear - yearBoundary;
```

Do you have any idea to fix ?

**Comment by buildingwatsize** [comment]
I'm not sure about your code but I think it probably issues with EcmaScript (ES2020)? in Nullish Coalescing Operator (see more [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator))

**Comment by buildingwatsize** [comment]
After a long time to wait for a response, I will close this issue. If you need any kind of help please re-open again. Thank you.
