### ISSUE TITLE
Module parse failed: Unexpected token (531:43)

### ISSUE THREAD

**Issue by pimpims** [buildingwatsize/thaidatepicker-react#5]
I cannot use it because this error.
./node_modules/thaidatepicker-react/dist/index.modern.js 531:43
Module parse failed: Unexpected token (531:43)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   const [value, setValue] = useState(props.value ? props.value : null);
|   const [selectedDate, setSelectedDate] = useState(value ? new Date(value) : null);     
>   const yearBoundary = props.yearBoundary ?? 99;
|   const thisYear = dayjs().year();
|   const minYear = props.minDate ? dayjs(props.minDate).year() : thisYear - yearBoundary;

**Comment by anupong-s** [comment]
same issue

**Comment by buildingwatsize** [comment]
I will update the dependency and version so I will re-check this problem after that. please be patient.

**Comment by buildingwatsize** [comment]
As I tested, I think it will not be a problem anymore. I will close this issue if you're stuck in this problem please create a new one.
