### ISSUE TITLE
Support for defaultProps will be removed from function components in a future major release

### ISSUE THREAD

**Issue by surapzero** [buildingwatsize/thaidatepicker-react#78]
ใช้ version 1.3.6 กับ nextjs พบปัญหา Support for defaultProps will be removed from function components in a future major release
ไม่ทราบว่าแก้ได้อย่างไรครับ

**Comment by buildingwatsize** [comment]
# ✅ Reproduced

## Environment:

- next: "14.2.7"
- react: "18.3.1"
- react-dom: "18.3.1",
- thaidatepicker-react: "1.3.6"

## Issues:

```bash
Warning: Ce: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```

## Explain:

1. เบื้องต้นพบว่าเป็น Log Level Warning ที่แจ้งเตือนว่า [React Release หน้า `React v19` ที่จะทำการลบ defaultProps ออกไป](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-deprecated-react-apis) ดังนั้นจึงยังคงสามารถใช้งานได้อยู่ใน `React@18.3.1`
2. ผมกำลัง Refactor Code เพื่อให้รองรับการทำงานในอนาคต หากดำเนินการเสร็จแล้วจะมาแจ้งใน Issue นี้พร้อม [Release](https://github.com/buildingwatsize/thaidatepicker-react/releases) ครับ
